image: Visual Studio 2017

cache: c:\tools\vcpkg\installed\

install:
  - vcpkg install boost-algorithm:x86-windows-static boost-format:x86-windows-static boost-asio:x86-windows-static boost-asio:x86-windows-static catch2:x86-windows-static

before_build:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static

configuration: RelWithDebInfo

build:
  project: build\Extron-Matrix.sln

test_script:
  - tests\unittests\RelWithDebInfo\Extron-Matrix_Unittests.exe ~[hardware-required]
  - tests\dll\RelWithDebInfo\Extron-Matrix_DLLTests.exe

artifacts:
  - path: build\RelWithDebInfo\Extron-Matrix.dll
  - path: build\RelWithDebInfo\Extron-Matrix.pdb
