image: Visual Studio 2017

cache: c:\tools\vcpkg\installed\

install:
  - vcpkg install boost-algorithm:x86-windows-static boost-format:x86-windows-static boost-asio:x86-windows-static boost-asio:x86-windows-static catch2:x86-windows-static

before_build:
  - ps: (Get-Content res\Extron-Matrix.rc).replace('0,0,0,0', $env:APPVEYOR_BUILD_VERSION.replace('.',',')).replace('0.0.0.0', $env:APPVEYOR_BUILD_VERSION) | Set-Content res\Extron-Matrix.rc
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static

configuration: RelWithDebInfo

build:
  project: build\Extron-Matrix.sln

after_build:
   - 7z a %APPVEYOR_BUILD_FOLDER%\Extron-Matrix-dll.zip %APPVEYOR_BUILD_FOLDER%\build\RelWithDebInfo\Extron-Matrix.dll
   - 7z a %APPVEYOR_BUILD_FOLDER%\Extron-Matrix-pdb.zip %APPVEYOR_BUILD_FOLDER%\build\RelWithDebInfo\Extron-Matrix.pdb

test_script:
  - tests\unittests\RelWithDebInfo\Extron-Matrix_Unittests.exe ~[hardware-required]
  - tests\dll\RelWithDebInfo\Extron-Matrix_DLLTests.exe

artifacts:
  - path: Extron-Matrix-dll.zip
  - path: Extron-Matrix-pdb.zip

skip_tags: true # We crreate tags as part of the deploy process

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: S9CG53vs2k5o/zvoY8Us4peL2S+kp9a8IDLmRaK6yxRx7o+fuPUctlU4qBqSsI6X
  on:
    branch: master
